import Header from "./Header";
import Head from "next/head";

export default function Layout({ children }) {
    return (
        <>
            <div className="head">
                <Head>
                    <title>Simba Money Transfer</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
            <Header />
            <div className="p-6">
                {children}
            </div>
        </>
    )
}
